package modele.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the QUESTION table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="QUESTION"
 */
public abstract class BaseQuestion  implements Serializable {

	public static String PROP_REPONSE_B = "ReponseB";
	public static String PROP_REPONSE_C = "ReponseC";
	public static String PROP_REPONSE_D = "ReponseD";
	public static String PROP_REPONSE_A = "ReponseA";
	public static String PROP_THEME = "Theme";
	public static String PROP_QUESTION = "Question";
	public static String PROP_ID = "Id";
	public static String PROP_BONNE_REPONSE = "BonneReponse";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _question;
	private java.lang.String _bonneReponse;
	private java.lang.String _reponseA;
	private java.lang.Integer _theme;
	private java.lang.String _reponseD;
	private java.lang.String _reponseB;
	private java.lang.String _reponseC;


	// constructors
	public BaseQuestion () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseQuestion (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseQuestion (
		java.lang.Integer _id,
		java.lang.Integer _theme) {

		this.setId(_id);
		this.setTheme(_theme);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: question
	 */
	public java.lang.String getQuestion () {
		return _question;
	}

	/**
	 * Set the value related to the column: question
	 * @param _question the question value
	 */
	public void setQuestion (java.lang.String _question) {
		this._question = _question;
	}


	/**
	 * Return the value associated with the column: bonneReponse
	 */
	public java.lang.String getBonneReponse () {
		return _bonneReponse;
	}

	/**
	 * Set the value related to the column: bonneReponse
	 * @param _bonneReponse the bonneReponse value
	 */
	public void setBonneReponse (java.lang.String _bonneReponse) {
		this._bonneReponse = _bonneReponse;
	}


	/**
	 * Return the value associated with the column: reponseA
	 */
	public java.lang.String getReponseA () {
		return _reponseA;
	}

	/**
	 * Set the value related to the column: reponseA
	 * @param _reponseA the reponseA value
	 */
	public void setReponseA (java.lang.String _reponseA) {
		this._reponseA = _reponseA;
	}


	/**
	 * Return the value associated with the column: theme
	 */
	public java.lang.Integer getTheme () {
		return _theme;
	}

	/**
	 * Set the value related to the column: theme
	 * @param _theme the theme value
	 */
	public void setTheme (java.lang.Integer _theme) {
		this._theme = _theme;
	}


	/**
	 * Return the value associated with the column: reponseD
	 */
	public java.lang.String getReponseD () {
		return _reponseD;
	}

	/**
	 * Set the value related to the column: reponseD
	 * @param _reponseD the reponseD value
	 */
	public void setReponseD (java.lang.String _reponseD) {
		this._reponseD = _reponseD;
	}


	/**
	 * Return the value associated with the column: reponseB
	 */
	public java.lang.String getReponseB () {
		return _reponseB;
	}

	/**
	 * Set the value related to the column: reponseB
	 * @param _reponseB the reponseB value
	 */
	public void setReponseB (java.lang.String _reponseB) {
		this._reponseB = _reponseB;
	}


	/**
	 * Return the value associated with the column: reponseC
	 */
	public java.lang.String getReponseC () {
		return _reponseC;
	}

	/**
	 * Set the value related to the column: reponseC
	 * @param _reponseC the reponseC value
	 */
	public void setReponseC (java.lang.String _reponseC) {
		this._reponseC = _reponseC;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof modele.base.BaseQuestion)) return false;
		else {
			modele.base.BaseQuestion mObj = (modele.base.BaseQuestion) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}