package modele.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the invitation table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="invitation"
 */
public abstract class BaseInvitation  implements Serializable {



	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _joueurEnAttente;
	private java.lang.Integer _joueurCreateur;


	// constructors
	public BaseInvitation () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseInvitation (
		java.lang.Integer _joueurEnAttente,
		java.lang.Integer _joueurCreateur) {

		this.setJoueurEnAttente(_joueurEnAttente);
		this.setJoueurCreateur(_joueurCreateur);
		initialize();
	}

	protected void initialize () {}



	/**
     * @hibernate.property
     *  column=joueurEnAttente
	 * not-null=true
	 */
	public java.lang.Integer getJoueurEnAttente () {
		return this._joueurEnAttente;
	}

	/**
	 * Set the value related to the column: joueurEnAttente
	 * @param _joueurEnAttente the joueurEnAttente value
	 */
	public void setJoueurEnAttente (java.lang.Integer _joueurEnAttente) {
		this._joueurEnAttente = _joueurEnAttente;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
     * @hibernate.property
     *  column=joueurCreateur
	 * not-null=true
	 */
	public java.lang.Integer getJoueurCreateur () {
		return this._joueurCreateur;
	}

	/**
	 * Set the value related to the column: joueurCreateur
	 * @param _joueurCreateur the joueurCreateur value
	 */
	public void setJoueurCreateur (java.lang.Integer _joueurCreateur) {
		this._joueurCreateur = _joueurCreateur;
		this.hashCode = Integer.MIN_VALUE;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof modele.Invitation)) return false;
		else {
			modele.Invitation mObj = (modele.Invitation) obj;
			if (null != this.getJoueurEnAttente() && null != mObj.getJoueurEnAttente()) {
				if (!this.getJoueurEnAttente().equals(mObj.getJoueurEnAttente())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getJoueurCreateur() && null != mObj.getJoueurCreateur()) {
				if (!this.getJoueurCreateur().equals(mObj.getJoueurCreateur())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getJoueurEnAttente()) {
				sb.append(this.getJoueurEnAttente().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getJoueurCreateur()) {
				sb.append(this.getJoueurCreateur().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}