package modele.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the ROUND table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="ROUND"
 */
public abstract class BaseRound  implements Serializable {

	public static String PROP_ID = "Id";
	public static String PROP_PARTIE = "partie";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// many to one
	private modele.Partie _partie;

	// collections
	private java.util.Set _questions;


	// constructors
	public BaseRound () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseRound (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseRound (
		java.lang.Integer _id,
		modele.Partie _partie) {

		this.setId(_id);
		this.setPartie(_partie);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=partie
	 * not-null=true
	 */
	public modele.Partie getPartie () {
		return this._partie;
	}

	/**
	 * Set the value related to the column: partie
	 * @param _partie the partie value
	 */
	public void setPartie (modele.Partie _partie) {
		this._partie = _partie;
	}


	/**
	 * Return the value associated with the column: questions
	 */
	public java.util.Set getQuestions () {
		return this._questions;
	}

	/**
	 * Set the value related to the column: questions
	 * @param _questions the questions value
	 */
	public void setQuestions (java.util.Set _questions) {
		this._questions = _questions;
	}
	
	public void addToQuestions (Object obj) {
		if (null == this._questions) this._questions = new java.util.HashSet();
		this._questions.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof modele.base.BaseRound)) return false;
		else {
			modele.base.BaseRound mObj = (modele.base.BaseRound) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}