package modele.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the reponse table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="reponse"
 */
public abstract class BaseReponse  implements Serializable {

	public static String PROP_REPONSE = "Reponse";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private modele.ReponsePK _id;

	// fields
	private java.lang.String _reponse;


	// constructors
	public BaseReponse () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseReponse (modele.ReponsePK _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public modele.ReponsePK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (modele.ReponsePK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: reponse
	 */
	public java.lang.String getReponse () {
		return _reponse;
	}

	/**
	 * Set the value related to the column: reponse
	 * @param _reponse the reponse value
	 */
	public void setReponse (java.lang.String _reponse) {
		this._reponse = _reponse;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof modele.base.BaseReponse)) return false;
		else {
			modele.base.BaseReponse mObj = (modele.base.BaseReponse) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}