package modele.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public class BaseReponsePK implements Serializable {

	private int hashCode = Integer.MIN_VALUE;

	private java.lang.Integer _round;
	private java.lang.Integer _question;
	private java.lang.Integer _joueur;

	public BaseReponsePK () {}
	
	public BaseReponsePK (
		java.lang.Integer _round,
		java.lang.Integer _question,
		java.lang.Integer _joueur) {

		this.setRound(_round);
		this.setQuestion(_question);
		this.setJoueur(_joueur);
	}


	public java.lang.Integer getRound () {
		return _round;
	}

	public void setRound (java.lang.Integer _round) {
		hashCode = Integer.MIN_VALUE;
		this._round = _round;
	}

	public java.lang.Integer getQuestion () {
		return _question;
	}

	public void setQuestion (java.lang.Integer _question) {
		hashCode = Integer.MIN_VALUE;
		this._question = _question;
	}

	public java.lang.Integer getJoueur () {
		return _joueur;
	}

	public void setJoueur (java.lang.Integer _joueur) {
		hashCode = Integer.MIN_VALUE;
		this._joueur = _joueur;
	}

	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof modele.ReponsePK)) return false;
		else {
			modele.ReponsePK mObj = (modele.ReponsePK) obj;
			if (null != this.getRound() && null != mObj.getRound()) {
				if (!this.getRound().equals(mObj.getRound())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getQuestion() && null != mObj.getQuestion()) {
				if (!this.getQuestion().equals(mObj.getQuestion())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getJoueur() && null != mObj.getJoueur()) {
				if (!this.getJoueur().equals(mObj.getJoueur())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}

	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getRound()) {
				sb.append(this.getRound().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getQuestion()) {
				sb.append(this.getQuestion().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getJoueur()) {
				sb.append(this.getJoueur().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}

}